/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import napakalaki.Treasure;

/**
 *
 * @author plhurtado
 */
public class TreasureView extends javax.swing.JPanel {

    /**
     * Creates new form TreasureView
     */
    private boolean selected=false;
    private Treasure treasureModel;
    public TreasureView() {
        initComponents();
    }
    
    public void setTreasure (Treasure t){
        treasureModel=t;
        name.setText(treasureModel.getName());
        min.setText(Integer.toString(treasureModel.getMinBonus()));
        max.setText(Integer.toString(treasureModel.getMaxBonus()));
        gold.setText(Integer.toString(treasureModel.getGoldCoins()));
        treasureKind.setText(treasureModel.getType().toString());
        repaint();
    }
    
    public boolean isSelected(){
        return this.selected;
    }
    
    public Treasure getTreasure(){
        return this.treasureModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimo = new javax.swing.JLabel();
        maximo = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        min = new javax.swing.JTextField();
        max = new javax.swing.JTextField();
        gold = new javax.swing.JTextField();
        treasureKind = new javax.swing.JTextField();
        valor1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 237, 237));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        minimo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        minimo.setForeground(new java.awt.Color(1, 1, 1));
        minimo.setText("Minimo");

        maximo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        maximo.setForeground(new java.awt.Color(1, 1, 1));
        maximo.setText("Maximo");

        name.setEditable(false);
        name.setBackground(new java.awt.Color(237, 237, 237));
        name.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });

        min.setEditable(false);
        min.setBackground(new java.awt.Color(237, 237, 237));
        min.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        min.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        max.setEditable(false);
        max.setBackground(new java.awt.Color(237, 237, 237));
        max.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        max.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        gold.setEditable(false);
        gold.setBackground(new java.awt.Color(237, 237, 237));
        gold.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        gold.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldActionPerformed(evt);
            }
        });

        treasureKind.setEditable(false);
        treasureKind.setBackground(new java.awt.Color(237, 237, 237));
        treasureKind.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        treasureKind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        treasureKind.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        valor1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        valor1.setForeground(new java.awt.Color(1, 1, 1));
        valor1.setText("Oro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(max)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimo)
                    .addComponent(maximo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(valor1)
                .addGap(26, 26, 26)
                .addComponent(gold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(treasureKind))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treasureKind, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maximo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor1)
                            .addComponent(gold, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (!isSelected()){
            selected=true;
            this.setBackground(Color.red);
        }
        else{
            selected=false;
            this.setBackground(Color.LIGHT_GRAY);
            
        }

        setOpaque(!this.selected);
        

       
        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void goldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goldActionPerformed

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gold;
    private javax.swing.JTextField max;
    private javax.swing.JLabel maximo;
    private javax.swing.JTextField min;
    private javax.swing.JLabel minimo;
    private javax.swing.JTextField name;
    private javax.swing.JTextField treasureKind;
    private javax.swing.JLabel valor1;
    // End of variables declaration//GEN-END:variables
}
